// <auto-generated />
using System;
using Lanflix.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lanflix.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251101154457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Lanflix.Domain.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Title");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("Type", "AddedAt");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StillPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TmdbId");

                    b.HasIndex("ContentId", "SeasonNumber", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKidsProfile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("Name");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.StreamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentPositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAudioCodec")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetBitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetVideoCodec")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscodingProcessId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastActivityAt");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.HasIndex("ProfileId", "IsActive");

                    b.ToTable("StreamSessions");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.WatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("WatchedPercentage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("LastWatchedAt");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId", "LastWatchedAt");

                    b.HasIndex("ProfileId", "ContentId", "EpisodeId")
                        .IsUnique();

                    b.ToTable("WatchHistories");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("ContentId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId", "AddedAt");

                    b.HasIndex("ProfileId", "ContentId")
                        .IsUnique();

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Content", b =>
                {
                    b.OwnsOne("Lanflix.Domain.ValueObjects.MediaInfo", "MediaInfo", b1 =>
                        {
                            b1.Property<int>("ContentId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Container")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("TEXT");

                            b1.Property<long>("FileSize")
                                .HasColumnType("INTEGER");

                            b1.Property<long?>("OverallBitrate")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ContentId");

                            b1.ToTable("Contents");

                            b1.ToJson("MediaInfo");

                            b1.WithOwner()
                                .HasForeignKey("ContentId");

                            b1.OwnsMany("Lanflix.Domain.ValueObjects.AudioStream", "Audio", b2 =>
                                {
                                    b2.Property<int>("MediaInfoContentId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<long>("Bitrate")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Channels")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Codec")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Index")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsDefault")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("SampleRate")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Title")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MediaInfoContentId", "__synthesizedOrdinal");

                                    b2.ToTable("Contents");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoContentId");
                                });

                            b1.OwnsMany("Lanflix.Domain.ValueObjects.SubtitleStream", "Subtitles", b2 =>
                                {
                                    b2.Property<int>("MediaInfoContentId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("ExternalFilePath")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Format")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Index")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsDefault")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsEmbedded")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsForced")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MediaInfoContentId", "__synthesizedOrdinal");

                                    b2.ToTable("Contents");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoContentId");
                                });

                            b1.OwnsOne("Lanflix.Domain.ValueObjects.VideoStream", "Video", b2 =>
                                {
                                    b2.Property<int>("MediaInfoContentId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<long>("Bitrate")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Codec")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ColorSpace")
                                        .HasColumnType("TEXT");

                                    b2.Property<double>("FrameRate")
                                        .HasColumnType("REAL");

                                    b2.Property<string>("HdrFormat")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Height")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsHDR")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("PixelFormat")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Width")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("MediaInfoContentId");

                                    b2.ToTable("Contents");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoContentId");
                                });

                            b1.Navigation("Audio");

                            b1.Navigation("Subtitles");

                            b1.Navigation("Video")
                                .IsRequired();
                        });

                    b.Navigation("MediaInfo");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Episode", b =>
                {
                    b.HasOne("Lanflix.Domain.Entities.Content", "Content")
                        .WithMany("Episodes")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lanflix.Domain.ValueObjects.MediaInfo", "MediaInfo", b1 =>
                        {
                            b1.Property<int>("EpisodeId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Container")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("TEXT");

                            b1.Property<long>("FileSize")
                                .HasColumnType("INTEGER");

                            b1.Property<long?>("OverallBitrate")
                                .HasColumnType("INTEGER");

                            b1.HasKey("EpisodeId");

                            b1.ToTable("Episodes");

                            b1.ToJson("MediaInfo");

                            b1.WithOwner()
                                .HasForeignKey("EpisodeId");

                            b1.OwnsMany("Lanflix.Domain.ValueObjects.AudioStream", "Audio", b2 =>
                                {
                                    b2.Property<int>("MediaInfoEpisodeId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<long>("Bitrate")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Channels")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Codec")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Index")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsDefault")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("SampleRate")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Title")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MediaInfoEpisodeId", "__synthesizedOrdinal");

                                    b2.ToTable("Episodes");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoEpisodeId");
                                });

                            b1.OwnsMany("Lanflix.Domain.ValueObjects.SubtitleStream", "Subtitles", b2 =>
                                {
                                    b2.Property<int>("MediaInfoEpisodeId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("ExternalFilePath")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Format")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Index")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsDefault")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsEmbedded")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsForced")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MediaInfoEpisodeId", "__synthesizedOrdinal");

                                    b2.ToTable("Episodes");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoEpisodeId");
                                });

                            b1.OwnsOne("Lanflix.Domain.ValueObjects.VideoStream", "Video", b2 =>
                                {
                                    b2.Property<int>("MediaInfoEpisodeId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<long>("Bitrate")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Codec")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ColorSpace")
                                        .HasColumnType("TEXT");

                                    b2.Property<double>("FrameRate")
                                        .HasColumnType("REAL");

                                    b2.Property<string>("HdrFormat")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Height")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsHDR")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("PixelFormat")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Width")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("MediaInfoEpisodeId");

                                    b2.ToTable("Episodes");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoEpisodeId");
                                });

                            b1.Navigation("Audio");

                            b1.Navigation("Subtitles");

                            b1.Navigation("Video")
                                .IsRequired();
                        });

                    b.Navigation("Content");

                    b.Navigation("MediaInfo");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Profile", b =>
                {
                    b.OwnsOne("Lanflix.Domain.ValueObjects.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<int>("ProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("AllowHardwareAcceleration")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("AutoPlayNextEpisode")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("AutoSkipIntro")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("MaxResolution")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PreferredAudioLanguage")
                                .HasColumnType("TEXT");

                            b1.Property<long?>("PreferredBitrate")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PreferredSubtitleLanguage")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("SubtitlesEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profiles");

                            b1.ToJson("Preferences");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.StreamSession", b =>
                {
                    b.HasOne("Lanflix.Domain.Entities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lanflix.Domain.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lanflix.Domain.Entities.Profile", "Profile")
                        .WithMany("StreamSessions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Episode");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.WatchHistory", b =>
                {
                    b.HasOne("Lanflix.Domain.Entities.Content", "Content")
                        .WithMany("WatchHistories")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lanflix.Domain.Entities.Episode", "Episode")
                        .WithMany("WatchHistories")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lanflix.Domain.Entities.Profile", "Profile")
                        .WithMany("WatchHistories")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Episode");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Watchlist", b =>
                {
                    b.HasOne("Lanflix.Domain.Entities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lanflix.Domain.Entities.Profile", "Profile")
                        .WithMany("Watchlists")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Content", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Episode", b =>
                {
                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Profile", b =>
                {
                    b.Navigation("StreamSessions");

                    b.Navigation("WatchHistories");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
