// <auto-generated />
using System;
using Lanflix.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lanflix.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801194003_LiveTvFoundation")]
    partial class LiveTvFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Lanflix.Domain.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Title");

                    b.HasIndex("TmdbId");

                    b.HasIndex("Type");

                    b.HasIndex("TmdbId", "Type")
                        .IsUnique();

                    b.HasIndex("Type", "AddedAt");

                    b.HasIndex("Type", "Rating");

                    b.HasIndex("Type", "ReleaseDate");

                    b.HasIndex("Type", "Title");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CreditsStartTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("IntroEndTime")
                        .HasColumnType("REAL");

                    b.Property<double?>("IntroStartTime")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StillPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TmdbId");

                    b.HasIndex("ContentId", "SeasonNumber", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.ServerSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ServerSettings", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Administration.BackgroundJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Name", "CreatedAtUtc");

                    b.ToTable("BackgroundJobRuns", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Devices.ClientDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAtUtc");

                    b.HasIndex("AccountId", "LastSeenAtUtc");

                    b.ToTable("ClientDevices", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Identity.AuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("AuditRecords", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Identity.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AbsoluteExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AccountId", "RevokedAtUtc");

                    b.ToTable("RefreshSessions", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Library.AccountWatchlistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ContentId")
                        .IsUnique();

                    b.HasIndex("AccountId", "CreatedAtUtc");

                    b.ToTable("AccountWatchlist", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.LiveTV.LiveTvChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamUri")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Enabled", "Number");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("LiveTvChannels", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.LiveTV.LiveTvFavorite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("AccountId", "ChannelId")
                        .IsUnique();

                    b.ToTable("LiveTvFavorites", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.LiveTV.LiveTvProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtworkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "ExternalId", "StartsAtUtc")
                        .IsUnique();

                    b.HasIndex("ChannelId", "StartsAtUtc", "EndsAtUtc");

                    b.ToTable("LiveTvPrograms", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.LiveTV.LiveTvSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuideUri")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRefreshedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTuners")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LiveTvSources", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.LiveTV.LiveTvTunerLease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("SourceId", "ExpiresAtUtc");

                    b.ToTable("LiveTvTunerLeases", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Metadata.ArtworkPalette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<int>("AlgorithmVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Depth")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Glow")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnBackground")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SourceLastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceLength")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentId")
                        .IsUnique();

                    b.ToTable("ArtworkPalettes", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicAlbum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtworkPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId", "NormalizedTitle")
                        .IsUnique();

                    b.ToTable("MusicAlbums", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicArtist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtworkPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MusicBrainzId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("MusicArtists", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicFavorite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("AccountId", "TrackId")
                        .IsUnique();

                    b.ToTable("MusicFavorites", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicLyrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId")
                        .IsUnique();

                    b.ToTable("MusicLyrics", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicPlayHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("AccountId", "PlayedAtUtc");

                    b.ToTable("MusicPlayHistory", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicPlaylist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique();

                    b.ToTable("MusicPlaylists", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicPlaylistTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("PlaylistId", "Position")
                        .IsUnique();

                    b.HasIndex("PlaylistId", "TrackId")
                        .IsUnique();

                    b.ToTable("MusicPlaylistTracks", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("AccountId", "Position")
                        .IsUnique();

                    b.ToTable("MusicQueueItems", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FileModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleRateHz")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("MusicBrainzId");

                    b.HasIndex("AlbumId", "DiscNumber", "TrackNumber");

                    b.ToTable("MusicTracks", (string)null);
                });

            modelBuilder.Entity("Lanflix.Modules.Playback.PlaybackProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "UpdatedAtUtc");

                    b.HasIndex("AccountId", "MediaKind", "MediaId")
                        .IsUnique();

                    b.ToTable("PlaybackProgress", (string)null);
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Content", b =>
                {
                    b.OwnsOne("Lanflix.Domain.ValueObjects.MediaInfo", "MediaInfo", b1 =>
                        {
                            b1.Property<int>("ContentId");

                            b1.Property<string>("Container")
                                .IsRequired();

                            b1.Property<TimeSpan>("Duration");

                            b1.Property<long>("FileSize");

                            b1.Property<long?>("OverallBitrate");

                            b1.HasKey("ContentId");

                            b1.ToTable("Contents");

                            b1.ToJson("MediaInfo");

                            b1.WithOwner()
                                .HasForeignKey("ContentId");

                            b1.OwnsMany("Lanflix.Domain.ValueObjects.AudioStream", "Audio", b2 =>
                                {
                                    b2.Property<int>("MediaInfoContentId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<long>("Bitrate");

                                    b2.Property<int>("Channels");

                                    b2.Property<string>("Codec")
                                        .IsRequired();

                                    b2.Property<int>("Index");

                                    b2.Property<bool>("IsDefault");

                                    b2.Property<string>("Language");

                                    b2.Property<int>("SampleRate");

                                    b2.Property<string>("Title");

                                    b2.HasKey("MediaInfoContentId", "__synthesizedOrdinal");

                                    b2.ToTable("Contents");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoContentId");
                                });

                            b1.OwnsMany("Lanflix.Domain.ValueObjects.SubtitleStream", "Subtitles", b2 =>
                                {
                                    b2.Property<int>("MediaInfoContentId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("ExternalFilePath");

                                    b2.Property<string>("Format")
                                        .IsRequired();

                                    b2.Property<int>("Index");

                                    b2.Property<bool>("IsDefault");

                                    b2.Property<bool>("IsEmbedded");

                                    b2.Property<bool>("IsForced");

                                    b2.Property<string>("Language");

                                    b2.Property<string>("Title");

                                    b2.HasKey("MediaInfoContentId", "__synthesizedOrdinal");

                                    b2.ToTable("Contents");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoContentId");
                                });

                            b1.OwnsOne("Lanflix.Domain.ValueObjects.VideoStream", "Video", b2 =>
                                {
                                    b2.Property<int>("MediaInfoContentId");

                                    b2.Property<long>("Bitrate");

                                    b2.Property<string>("Codec")
                                        .IsRequired();

                                    b2.Property<string>("ColorSpace");

                                    b2.Property<double>("FrameRate");

                                    b2.Property<string>("HdrFormat");

                                    b2.Property<int>("Height");

                                    b2.Property<bool>("IsHDR");

                                    b2.Property<string>("PixelFormat")
                                        .IsRequired();

                                    b2.Property<int>("Width");

                                    b2.HasKey("MediaInfoContentId");

                                    b2.ToTable("Contents");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoContentId");
                                });

                            b1.Navigation("Audio");

                            b1.Navigation("Subtitles");

                            b1.Navigation("Video")
                                .IsRequired();
                        });

                    b.Navigation("MediaInfo");
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Episode", b =>
                {
                    b.HasOne("Lanflix.Domain.Entities.Content", "Content")
                        .WithMany("Episodes")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lanflix.Domain.ValueObjects.MediaInfo", "MediaInfo", b1 =>
                        {
                            b1.Property<int>("EpisodeId");

                            b1.Property<string>("Container")
                                .IsRequired();

                            b1.Property<TimeSpan>("Duration");

                            b1.Property<long>("FileSize");

                            b1.Property<long?>("OverallBitrate");

                            b1.HasKey("EpisodeId");

                            b1.ToTable("Episodes");

                            b1.ToJson("MediaInfo");

                            b1.WithOwner()
                                .HasForeignKey("EpisodeId");

                            b1.OwnsMany("Lanflix.Domain.ValueObjects.AudioStream", "Audio", b2 =>
                                {
                                    b2.Property<int>("MediaInfoEpisodeId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<long>("Bitrate");

                                    b2.Property<int>("Channels");

                                    b2.Property<string>("Codec")
                                        .IsRequired();

                                    b2.Property<int>("Index");

                                    b2.Property<bool>("IsDefault");

                                    b2.Property<string>("Language");

                                    b2.Property<int>("SampleRate");

                                    b2.Property<string>("Title");

                                    b2.HasKey("MediaInfoEpisodeId", "__synthesizedOrdinal");

                                    b2.ToTable("Episodes");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoEpisodeId");
                                });

                            b1.OwnsMany("Lanflix.Domain.ValueObjects.SubtitleStream", "Subtitles", b2 =>
                                {
                                    b2.Property<int>("MediaInfoEpisodeId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("ExternalFilePath");

                                    b2.Property<string>("Format")
                                        .IsRequired();

                                    b2.Property<int>("Index");

                                    b2.Property<bool>("IsDefault");

                                    b2.Property<bool>("IsEmbedded");

                                    b2.Property<bool>("IsForced");

                                    b2.Property<string>("Language");

                                    b2.Property<string>("Title");

                                    b2.HasKey("MediaInfoEpisodeId", "__synthesizedOrdinal");

                                    b2.ToTable("Episodes");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoEpisodeId");
                                });

                            b1.OwnsOne("Lanflix.Domain.ValueObjects.VideoStream", "Video", b2 =>
                                {
                                    b2.Property<int>("MediaInfoEpisodeId");

                                    b2.Property<long>("Bitrate");

                                    b2.Property<string>("Codec")
                                        .IsRequired();

                                    b2.Property<string>("ColorSpace");

                                    b2.Property<double>("FrameRate");

                                    b2.Property<string>("HdrFormat");

                                    b2.Property<int>("Height");

                                    b2.Property<bool>("IsHDR");

                                    b2.Property<string>("PixelFormat")
                                        .IsRequired();

                                    b2.Property<int>("Width");

                                    b2.HasKey("MediaInfoEpisodeId");

                                    b2.ToTable("Episodes");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInfoEpisodeId");
                                });

                            b1.Navigation("Audio");

                            b1.Navigation("Subtitles");

                            b1.Navigation("Video")
                                .IsRequired();
                        });

                    b.Navigation("Content");

                    b.Navigation("MediaInfo");
                });

            modelBuilder.Entity("Lanflix.Modules.Identity.RefreshSession", b =>
                {
                    b.HasOne("Lanflix.Modules.Identity.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Lanflix.Modules.LiveTV.LiveTvChannel", b =>
                {
                    b.HasOne("Lanflix.Modules.LiveTV.LiveTvSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.LiveTV.LiveTvFavorite", b =>
                {
                    b.HasOne("Lanflix.Modules.LiveTV.LiveTvChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.LiveTV.LiveTvProgram", b =>
                {
                    b.HasOne("Lanflix.Modules.LiveTV.LiveTvChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.LiveTV.LiveTvTunerLease", b =>
                {
                    b.HasOne("Lanflix.Modules.LiveTV.LiveTvChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lanflix.Modules.LiveTV.LiveTvSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicAlbum", b =>
                {
                    b.HasOne("Lanflix.Modules.Music.MusicArtist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicFavorite", b =>
                {
                    b.HasOne("Lanflix.Modules.Music.MusicTrack", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicLyrics", b =>
                {
                    b.HasOne("Lanflix.Modules.Music.MusicTrack", null)
                        .WithOne()
                        .HasForeignKey("Lanflix.Modules.Music.MusicLyrics", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicPlayHistory", b =>
                {
                    b.HasOne("Lanflix.Modules.Music.MusicTrack", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicPlaylistTrack", b =>
                {
                    b.HasOne("Lanflix.Modules.Music.MusicPlaylist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lanflix.Modules.Music.MusicTrack", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicQueueItem", b =>
                {
                    b.HasOne("Lanflix.Modules.Music.MusicTrack", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Modules.Music.MusicTrack", b =>
                {
                    b.HasOne("Lanflix.Modules.Music.MusicAlbum", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lanflix.Modules.Music.MusicArtist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lanflix.Domain.Entities.Content", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
