<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Lanflix.Modules.Realtime</RootNamespace></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\Lanflix.SharedKernel.csproj" />
  </ItemGroup>
</Project>
